project_id = "njddyppgxohfuvvjdslv"

[functions.create-checkout-box-variants]
verify_jwt = false

[functions.create-nyva-checkout]
verify_jwt = false

[functions.nyva-webhook]
verify_jwt = false

[functions.nyva-debug]
verify_jwt = false

[functions.create-nyva-embed]
verify_jwt = false

[functions.create-nyva-paylink]
verify_jwt = false

